apiVersion: v2
name: eo-auth
description: A Helm chart for Kubernetes

type: application
version: v0.1.2

dependencies:
  - name: eo-base-helm-chart
    version: "v0.4.5"
    repository: "https://energinet-datahub.github.io/helm-charts/"
