{{- range .Values.deployments}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ett-auth.fullname" $ }}-{{ .name }}
  labels:
    {{- include "ett-auth.labels" $ | nindent 4 }}
    component: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "ett-auth.selectorLabels" $ | nindent 6 }}
      component: {{ .name }}
  template:
    metadata:
      labels:
        {{- include "ett-auth.selectorLabels" $ | nindent 8 }}
        component: {{ .name }}
    spec:
      containers:
        - name: {{ $.Chart.Name }}-{{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- if .command }}
          command: [{{ .command | quote }}]
          {{- if .args }}
          args: [{{ .args | quote }}]
          {{- end}}
          {{- end}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .probes }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          {{- end }}
          {{- if .env}}
          env:
          {{- range $key, $value := .env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end}}
          {{- end}}
{{- end }}

