name: Lint and test

env:
  python-version: 3.8

on:
  push:
    branches:
      - main

  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev

  # removed temporarily
  # lint:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Set up Python ${{ env.python-version }}
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: ${{ env.python-version }}

  #   - name: Install pipenv
  #     run: |
  #       python -m pip install --upgrade pipenv wheel

  #   - id: cache-pipenv
  #     uses: actions/cache@v1
  #     with:
  #       path: ~/.local/share/virtualenvs
  #       key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

  #   - name: Analysing the code with flake8
  #     run: pipenv run lint-flake8

  unittest:
    name: Unittest
    # needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Running unittests
        run: |
          pipenv run unittest

  integrationtest:
    name: Integrationtest
    needs: unittest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Running integrationtest
        run: |
          pipenv run integrationtest
